//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRProject.SQLTrans {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurantes", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Restaurantes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REFERENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RATE {
            get {
                return this.RATEField;
            }
            set {
                if ((object.ReferenceEquals(this.RATEField, value) != true)) {
                    this.RATEField = value;
                    this.RaisePropertyChanged("RATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCIA {
            get {
                return this.REFERENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.REFERENCIAField, value) != true)) {
                    this.REFERENCIAField = value;
                    this.RaisePropertyChanged("REFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ADMINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREO_ELECTRONICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_CUMPLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VISITASField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ADMIN {
            get {
                return this.ADMINField;
            }
            set {
                if ((this.ADMINField.Equals(value) != true)) {
                    this.ADMINField = value;
                    this.RaisePropertyChanged("ADMIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO {
            get {
                return this.APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOField, value) != true)) {
                    this.APELLIDOField = value;
                    this.RaisePropertyChanged("APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_ELECTRONICO {
            get {
                return this.CORREO_ELECTRONICOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_ELECTRONICOField, value) != true)) {
                    this.CORREO_ELECTRONICOField = value;
                    this.RaisePropertyChanged("CORREO_ELECTRONICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_CUMPLE {
            get {
                return this.FECHA_CUMPLEField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_CUMPLEField, value) != true)) {
                    this.FECHA_CUMPLEField = value;
                    this.RaisePropertyChanged("FECHA_CUMPLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_USUARIOField, value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VISITAS {
            get {
                return this.VISITASField;
            }
            set {
                if ((this.VISITASField.Equals(value) != true)) {
                    this.VISITASField = value;
                    this.RaisePropertyChanged("VISITAS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platillos", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Platillos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PLATILLOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_RESTAURANTESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESTAURANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAField, value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PLATILLOS {
            get {
                return this.ID_PLATILLOSField;
            }
            set {
                if ((this.ID_PLATILLOSField.Equals(value) != true)) {
                    this.ID_PLATILLOSField = value;
                    this.RaisePropertyChanged("ID_PLATILLOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_RESTAURANTES {
            get {
                return this.ID_RESTAURANTESField;
            }
            set {
                if ((this.ID_RESTAURANTESField.Equals(value) != true)) {
                    this.ID_RESTAURANTESField = value;
                    this.RaisePropertyChanged("ID_RESTAURANTES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO {
            get {
                return this.ID_TIPOField;
            }
            set {
                if ((this.ID_TIPOField.Equals(value) != true)) {
                    this.ID_TIPOField = value;
                    this.RaisePropertyChanged("ID_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRECIO {
            get {
                return this.PRECIOField;
            }
            set {
                if ((this.PRECIOField.Equals(value) != true)) {
                    this.PRECIOField = value;
                    this.RaisePropertyChanged("PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RATE {
            get {
                return this.RATEField;
            }
            set {
                if ((this.RATEField.Equals(value) != true)) {
                    this.RATEField = value;
                    this.RaisePropertyChanged("RATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESTAURANTE {
            get {
                return this.RESTAURANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.RESTAURANTEField, value) != true)) {
                    this.RESTAURANTEField = value;
                    this.RaisePropertyChanged("RESTAURANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOField, value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comentarios", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Comentarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMENTARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_COMENTARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PLATILLOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMENTARIOS {
            get {
                return this.COMENTARIOSField;
            }
            set {
                if ((object.ReferenceEquals(this.COMENTARIOSField, value) != true)) {
                    this.COMENTARIOSField = value;
                    this.RaisePropertyChanged("COMENTARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAField, value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_COMENTARIOS {
            get {
                return this.ID_COMENTARIOSField;
            }
            set {
                if ((this.ID_COMENTARIOSField.Equals(value) != true)) {
                    this.ID_COMENTARIOSField = value;
                    this.RaisePropertyChanged("ID_COMENTARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PLATILLOS {
            get {
                return this.ID_PLATILLOSField;
            }
            set {
                if ((this.ID_PLATILLOSField.Equals(value) != true)) {
                    this.ID_PLATILLOSField = value;
                    this.RaisePropertyChanged("ID_PLATILLOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_USUARIOField, value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASS {
            get {
                return this.PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSField, value) != true)) {
                    this.PASSField = value;
                    this.RaisePropertyChanged("PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                if ((this.isAdminField.Equals(value) != true)) {
                    this.isAdminField = value;
                    this.RaisePropertyChanged("isAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Logs", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Logs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ACTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_OBJETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TABLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char TIPOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREACION {
            get {
                return this.CREACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.CREACIONField, value) != true)) {
                    this.CREACIONField = value;
                    this.RaisePropertyChanged("CREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ACTION {
            get {
                return this.ID_ACTIONField;
            }
            set {
                if ((this.ID_ACTIONField.Equals(value) != true)) {
                    this.ID_ACTIONField = value;
                    this.RaisePropertyChanged("ID_ACTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_OBJETO {
            get {
                return this.ID_OBJETOField;
            }
            set {
                if ((this.ID_OBJETOField.Equals(value) != true)) {
                    this.ID_OBJETOField = value;
                    this.RaisePropertyChanged("ID_OBJETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_USUARIOField, value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TABLA {
            get {
                return this.TABLAField;
            }
            set {
                if ((object.ReferenceEquals(this.TABLAField, value) != true)) {
                    this.TABLAField = value;
                    this.RaisePropertyChanged("TABLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((this.TIPOField.Equals(value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteType", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    public enum DeleteType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Restaurante = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Platillo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comentario = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLTrans.ICrudService")]
    public interface ICrudService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/isAdmin", ReplyAction="http://tempuri.org/ICrudService/isAdminResponse")]
        bool isAdmin(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/isAdmin", ReplyAction="http://tempuri.org/ICrudService/isAdminResponse")]
        System.Threading.Tasks.Task<bool> isAdminAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetRestaurante", ReplyAction="http://tempuri.org/ICrudService/GetRestauranteResponse")]
        PRProject.SQLTrans.Restaurantes[] GetRestaurante(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetRestaurante", ReplyAction="http://tempuri.org/ICrudService/GetRestauranteResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Restaurantes[]> GetRestauranteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetRestaurantes", ReplyAction="http://tempuri.org/ICrudService/GetRestaurantesResponse")]
        PRProject.SQLTrans.Restaurantes[] GetRestaurantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetRestaurantes", ReplyAction="http://tempuri.org/ICrudService/GetRestaurantesResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Restaurantes[]> GetRestaurantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetUsuario", ReplyAction="http://tempuri.org/ICrudService/GetUsuarioResponse")]
        PRProject.SQLTrans.Usuarios[] GetUsuario(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetUsuario", ReplyAction="http://tempuri.org/ICrudService/GetUsuarioResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Usuarios[]> GetUsuarioAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetUsuarios", ReplyAction="http://tempuri.org/ICrudService/GetUsuariosResponse")]
        PRProject.SQLTrans.Usuarios[] GetUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetUsuarios", ReplyAction="http://tempuri.org/ICrudService/GetUsuariosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Usuarios[]> GetUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetPlatillo", ReplyAction="http://tempuri.org/ICrudService/GetPlatilloResponse")]
        PRProject.SQLTrans.Platillos[] GetPlatillo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetPlatillo", ReplyAction="http://tempuri.org/ICrudService/GetPlatilloResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> GetPlatilloAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetPlatillos", ReplyAction="http://tempuri.org/ICrudService/GetPlatillosResponse")]
        PRProject.SQLTrans.Platillos[] GetPlatillos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetPlatillos", ReplyAction="http://tempuri.org/ICrudService/GetPlatillosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> GetPlatillosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetComentarios", ReplyAction="http://tempuri.org/ICrudService/GetComentariosResponse")]
        PRProject.SQLTrans.Comentarios[] GetComentarios(int id_platillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetComentarios", ReplyAction="http://tempuri.org/ICrudService/GetComentariosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Comentarios[]> GetComentariosAsync(int id_platillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetLastsComentarios", ReplyAction="http://tempuri.org/ICrudService/GetLastsComentariosResponse")]
        PRProject.SQLTrans.Comentarios[] GetLastsComentarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetLastsComentarios", ReplyAction="http://tempuri.org/ICrudService/GetLastsComentariosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Comentarios[]> GetLastsComentariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetTiposPlatillo", ReplyAction="http://tempuri.org/ICrudService/GetTiposPlatilloResponse")]
        string[] GetTiposPlatillo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetTiposPlatillo", ReplyAction="http://tempuri.org/ICrudService/GetTiposPlatilloResponse")]
        System.Threading.Tasks.Task<string[]> GetTiposPlatilloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_UltimosPlatillos", ReplyAction="http://tempuri.org/ICrudService/sp_UltimosPlatillosResponse")]
        PRProject.SQLTrans.Platillos[] sp_UltimosPlatillos(int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_UltimosPlatillos", ReplyAction="http://tempuri.org/ICrudService/sp_UltimosPlatillosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> sp_UltimosPlatillosAsync(int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetLogs", ReplyAction="http://tempuri.org/ICrudService/GetLogsResponse")]
        PRProject.SQLTrans.Logs[] GetLogs(PRProject.SQLTrans.LoginData login, int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetLogs", ReplyAction="http://tempuri.org/ICrudService/GetLogsResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Logs[]> GetLogsAsync(PRProject.SQLTrans.LoginData login, int offset, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Count", ReplyAction="http://tempuri.org/ICrudService/CountResponse")]
        int Count(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/Count", ReplyAction="http://tempuri.org/ICrudService/CountResponse")]
        System.Threading.Tasks.Task<int> CountAsync(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetValoracion", ReplyAction="http://tempuri.org/ICrudService/GetValoracionResponse")]
        int GetValoracion(string user, int platillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetValoracion", ReplyAction="http://tempuri.org/ICrudService/GetValoracionResponse")]
        System.Threading.Tasks.Task<int> GetValoracionAsync(string user, int platillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarRestaurante", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarRestauranteResponse")]
        void sp_AgregarRestaurante(PRProject.SQLTrans.LoginData login, string name, string reference, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarRestaurante", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarRestauranteResponse")]
        System.Threading.Tasks.Task sp_AgregarRestauranteAsync(PRProject.SQLTrans.LoginData login, string name, string reference, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarUsuarioResponse")]
        void sp_AgregarUsuario(string id, string nombre, string apellido, string correo, string borndate, string pass, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarUsuarioResponse")]
        System.Threading.Tasks.Task sp_AgregarUsuarioAsync(string id, string nombre, string apellido, string correo, string borndate, string pass, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_ValidarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_ValidarUsuarioResponse")]
        System.Data.DataSet sp_ValidarUsuario(string iduser, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_ValidarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> sp_ValidarUsuarioAsync(string iduser, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarImagen", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarImagenResponse")]
        int sp_AgregarImagen(PRProject.SQLTrans.LoginData login, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarImagen", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarImagenResponse")]
        System.Threading.Tasks.Task<int> sp_AgregarImagenAsync(PRProject.SQLTrans.LoginData login, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPlatilloResponse")]
        void sp_AgregarPlatillo(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPlatilloResponse")]
        System.Threading.Tasks.Task sp_AgregarPlatilloAsync(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPunto", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPuntoResponse")]
        void sp_AgregarPunto(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPunto", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPuntoResponse")]
        System.Threading.Tasks.Task sp_AgregarPuntoAsync(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarEstadistica", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarEstadisticaResponse")]
        void sp_AgregarEstadistica(PRProject.SQLTrans.LoginData login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarEstadistica", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarEstadisticaResponse")]
        System.Threading.Tasks.Task sp_AgregarEstadisticaAsync(PRProject.SQLTrans.LoginData login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarComentarioResponse")]
        void sp_AgregarComentario(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarComentarioResponse")]
        System.Threading.Tasks.Task sp_AgregarComentarioAsync(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarValoracion", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarValoracionResponse")]
        void sp_AgregarValoracion(PRProject.SQLTrans.LoginData login, string idplatillo, float rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarValoracion", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarValoracionResponse")]
        System.Threading.Tasks.Task sp_AgregarValoracionAsync(PRProject.SQLTrans.LoginData login, string idplatillo, float rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_Delete", ReplyAction="http://tempuri.org/ICrudService/sp_DeleteResponse")]
        void sp_Delete(PRProject.SQLTrans.LoginData login, PRProject.SQLTrans.DeleteType Tipo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_Delete", ReplyAction="http://tempuri.org/ICrudService/sp_DeleteResponse")]
        System.Threading.Tasks.Task sp_DeleteAsync(PRProject.SQLTrans.LoginData login, PRProject.SQLTrans.DeleteType Tipo, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterRestaurant", ReplyAction="http://tempuri.org/ICrudService/sp_AlterRestaurantResponse")]
        void sp_AlterRestaurant(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterRestaurant", ReplyAction="http://tempuri.org/ICrudService/sp_AlterRestaurantResponse")]
        System.Threading.Tasks.Task sp_AlterRestaurantAsync(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AlterPlatilloResponse")]
        void sp_AlterPlatillo(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AlterPlatilloResponse")]
        System.Threading.Tasks.Task sp_AlterPlatilloAsync(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterComentarioResponse")]
        void sp_AlterComentario(PRProject.SQLTrans.LoginData login, int id, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterComentarioResponse")]
        System.Threading.Tasks.Task sp_AlterComentarioAsync(PRProject.SQLTrans.LoginData login, int id, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterUsuarioResponse")]
        void sp_AlterUsuario(PRProject.SQLTrans.LoginData login, string username, int image, string nombre, string apellido, string correo, string birth, bool admin, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterUsuarioResponse")]
        System.Threading.Tasks.Task sp_AlterUsuarioAsync(PRProject.SQLTrans.LoginData login, string username, int image, string nombre, string apellido, string correo, string birth, bool admin, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_RecomendarProductos", ReplyAction="http://tempuri.org/ICrudService/sp_RecomendarProductosResponse")]
        PRProject.SQLTrans.Platillos[] sp_RecomendarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_RecomendarProductos", ReplyAction="http://tempuri.org/ICrudService/sp_RecomendarProductosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> sp_RecomendarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_RecomendarProductosPersonalizado", ReplyAction="http://tempuri.org/ICrudService/sp_RecomendarProductosPersonalizadoResponse")]
        PRProject.SQLTrans.Platillos[] sp_RecomendarProductosPersonalizado(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_RecomendarProductosPersonalizado", ReplyAction="http://tempuri.org/ICrudService/sp_RecomendarProductosPersonalizadoResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> sp_RecomendarProductosPersonalizadoAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarClick", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarClickResponse")]
        void sp_AgregarClick(PRProject.SQLTrans.LoginData login, int idplatillo, string iduser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarClick", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarClickResponse")]
        System.Threading.Tasks.Task sp_AgregarClickAsync(PRProject.SQLTrans.LoginData login, int idplatillo, string iduser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/getGallery", ReplyAction="http://tempuri.org/ICrudService/getGalleryResponse")]
        System.Collections.Generic.Dictionary<int, string> getGallery();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/getGallery", ReplyAction="http://tempuri.org/ICrudService/getGalleryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getGalleryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/buscarPlatillo", ReplyAction="http://tempuri.org/ICrudService/buscarPlatilloResponse")]
        PRProject.SQLTrans.Platillos[] buscarPlatillo(string buscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/buscarPlatillo", ReplyAction="http://tempuri.org/ICrudService/buscarPlatilloResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> buscarPlatilloAsync(string buscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterLocation", ReplyAction="http://tempuri.org/ICrudService/sp_AlterLocationResponse")]
        void sp_AlterLocation(PRProject.SQLTrans.LoginData login, int id, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterLocation", ReplyAction="http://tempuri.org/ICrudService/sp_AlterLocationResponse")]
        System.Threading.Tasks.Task sp_AlterLocationAsync(PRProject.SQLTrans.LoginData login, int id, int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrudServiceChannel : PRProject.SQLTrans.ICrudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudServiceClient : System.ServiceModel.ClientBase<PRProject.SQLTrans.ICrudService>, PRProject.SQLTrans.ICrudService {
        
        public CrudServiceClient() {
        }
        
        public CrudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isAdmin(string user) {
            return base.Channel.isAdmin(user);
        }
        
        public System.Threading.Tasks.Task<bool> isAdminAsync(string user) {
            return base.Channel.isAdminAsync(user);
        }
        
        public PRProject.SQLTrans.Restaurantes[] GetRestaurante(int id) {
            return base.Channel.GetRestaurante(id);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Restaurantes[]> GetRestauranteAsync(int id) {
            return base.Channel.GetRestauranteAsync(id);
        }
        
        public PRProject.SQLTrans.Restaurantes[] GetRestaurantes() {
            return base.Channel.GetRestaurantes();
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Restaurantes[]> GetRestaurantesAsync() {
            return base.Channel.GetRestaurantesAsync();
        }
        
        public PRProject.SQLTrans.Usuarios[] GetUsuario(string id) {
            return base.Channel.GetUsuario(id);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Usuarios[]> GetUsuarioAsync(string id) {
            return base.Channel.GetUsuarioAsync(id);
        }
        
        public PRProject.SQLTrans.Usuarios[] GetUsuarios() {
            return base.Channel.GetUsuarios();
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Usuarios[]> GetUsuariosAsync() {
            return base.Channel.GetUsuariosAsync();
        }
        
        public PRProject.SQLTrans.Platillos[] GetPlatillo(int id) {
            return base.Channel.GetPlatillo(id);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> GetPlatilloAsync(int id) {
            return base.Channel.GetPlatilloAsync(id);
        }
        
        public PRProject.SQLTrans.Platillos[] GetPlatillos() {
            return base.Channel.GetPlatillos();
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> GetPlatillosAsync() {
            return base.Channel.GetPlatillosAsync();
        }
        
        public PRProject.SQLTrans.Comentarios[] GetComentarios(int id_platillo) {
            return base.Channel.GetComentarios(id_platillo);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Comentarios[]> GetComentariosAsync(int id_platillo) {
            return base.Channel.GetComentariosAsync(id_platillo);
        }
        
        public PRProject.SQLTrans.Comentarios[] GetLastsComentarios() {
            return base.Channel.GetLastsComentarios();
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Comentarios[]> GetLastsComentariosAsync() {
            return base.Channel.GetLastsComentariosAsync();
        }
        
        public string[] GetTiposPlatillo() {
            return base.Channel.GetTiposPlatillo();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTiposPlatilloAsync() {
            return base.Channel.GetTiposPlatilloAsync();
        }
        
        public PRProject.SQLTrans.Platillos[] sp_UltimosPlatillos(int offset, int count) {
            return base.Channel.sp_UltimosPlatillos(offset, count);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> sp_UltimosPlatillosAsync(int offset, int count) {
            return base.Channel.sp_UltimosPlatillosAsync(offset, count);
        }
        
        public PRProject.SQLTrans.Logs[] GetLogs(PRProject.SQLTrans.LoginData login, int offset, int count) {
            return base.Channel.GetLogs(login, offset, count);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Logs[]> GetLogsAsync(PRProject.SQLTrans.LoginData login, int offset, int count) {
            return base.Channel.GetLogsAsync(login, offset, count);
        }
        
        public int Count(string table) {
            return base.Channel.Count(table);
        }
        
        public System.Threading.Tasks.Task<int> CountAsync(string table) {
            return base.Channel.CountAsync(table);
        }
        
        public int GetValoracion(string user, int platillo) {
            return base.Channel.GetValoracion(user, platillo);
        }
        
        public System.Threading.Tasks.Task<int> GetValoracionAsync(string user, int platillo) {
            return base.Channel.GetValoracionAsync(user, platillo);
        }
        
        public void sp_AgregarRestaurante(PRProject.SQLTrans.LoginData login, string name, string reference, string img) {
            base.Channel.sp_AgregarRestaurante(login, name, reference, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarRestauranteAsync(PRProject.SQLTrans.LoginData login, string name, string reference, string img) {
            return base.Channel.sp_AgregarRestauranteAsync(login, name, reference, img);
        }
        
        public void sp_AgregarUsuario(string id, string nombre, string apellido, string correo, string borndate, string pass, string img) {
            base.Channel.sp_AgregarUsuario(id, nombre, apellido, correo, borndate, pass, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarUsuarioAsync(string id, string nombre, string apellido, string correo, string borndate, string pass, string img) {
            return base.Channel.sp_AgregarUsuarioAsync(id, nombre, apellido, correo, borndate, pass, img);
        }
        
        public System.Data.DataSet sp_ValidarUsuario(string iduser, string pass) {
            return base.Channel.sp_ValidarUsuario(iduser, pass);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> sp_ValidarUsuarioAsync(string iduser, string pass) {
            return base.Channel.sp_ValidarUsuarioAsync(iduser, pass);
        }
        
        public int sp_AgregarImagen(PRProject.SQLTrans.LoginData login, string url) {
            return base.Channel.sp_AgregarImagen(login, url);
        }
        
        public System.Threading.Tasks.Task<int> sp_AgregarImagenAsync(PRProject.SQLTrans.LoginData login, string url) {
            return base.Channel.sp_AgregarImagenAsync(login, url);
        }
        
        public void sp_AgregarPlatillo(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img) {
            base.Channel.sp_AgregarPlatillo(login, nombre, precio, descripcion, tipo, restaurante, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarPlatilloAsync(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img) {
            return base.Channel.sp_AgregarPlatilloAsync(login, nombre, precio, descripcion, tipo, restaurante, img);
        }
        
        public void sp_AgregarPunto(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante) {
            base.Channel.sp_AgregarPunto(login, x, y, restaurante);
        }
        
        public System.Threading.Tasks.Task sp_AgregarPuntoAsync(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante) {
            return base.Channel.sp_AgregarPuntoAsync(login, x, y, restaurante);
        }
        
        public void sp_AgregarEstadistica(PRProject.SQLTrans.LoginData login) {
            base.Channel.sp_AgregarEstadistica(login);
        }
        
        public System.Threading.Tasks.Task sp_AgregarEstadisticaAsync(PRProject.SQLTrans.LoginData login) {
            return base.Channel.sp_AgregarEstadisticaAsync(login);
        }
        
        public void sp_AgregarComentario(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario) {
            base.Channel.sp_AgregarComentario(login, idplatillo, comentario);
        }
        
        public System.Threading.Tasks.Task sp_AgregarComentarioAsync(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario) {
            return base.Channel.sp_AgregarComentarioAsync(login, idplatillo, comentario);
        }
        
        public void sp_AgregarValoracion(PRProject.SQLTrans.LoginData login, string idplatillo, float rate) {
            base.Channel.sp_AgregarValoracion(login, idplatillo, rate);
        }
        
        public System.Threading.Tasks.Task sp_AgregarValoracionAsync(PRProject.SQLTrans.LoginData login, string idplatillo, float rate) {
            return base.Channel.sp_AgregarValoracionAsync(login, idplatillo, rate);
        }
        
        public void sp_Delete(PRProject.SQLTrans.LoginData login, PRProject.SQLTrans.DeleteType Tipo, int id) {
            base.Channel.sp_Delete(login, Tipo, id);
        }
        
        public System.Threading.Tasks.Task sp_DeleteAsync(PRProject.SQLTrans.LoginData login, PRProject.SQLTrans.DeleteType Tipo, int id) {
            return base.Channel.sp_DeleteAsync(login, Tipo, id);
        }
        
        public void sp_AlterRestaurant(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia) {
            base.Channel.sp_AlterRestaurant(login, id, img, point, nombre, referencia);
        }
        
        public System.Threading.Tasks.Task sp_AlterRestaurantAsync(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia) {
            return base.Channel.sp_AlterRestaurantAsync(login, id, img, point, nombre, referencia);
        }
        
        public void sp_AlterPlatillo(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion) {
            base.Channel.sp_AlterPlatillo(login, id, restaurant, img, tipo, nombre, precio, descripcion);
        }
        
        public System.Threading.Tasks.Task sp_AlterPlatilloAsync(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion) {
            return base.Channel.sp_AlterPlatilloAsync(login, id, restaurant, img, tipo, nombre, precio, descripcion);
        }
        
        public void sp_AlterComentario(PRProject.SQLTrans.LoginData login, int id, string comentario) {
            base.Channel.sp_AlterComentario(login, id, comentario);
        }
        
        public System.Threading.Tasks.Task sp_AlterComentarioAsync(PRProject.SQLTrans.LoginData login, int id, string comentario) {
            return base.Channel.sp_AlterComentarioAsync(login, id, comentario);
        }
        
        public void sp_AlterUsuario(PRProject.SQLTrans.LoginData login, string username, int image, string nombre, string apellido, string correo, string birth, bool admin, string password) {
            base.Channel.sp_AlterUsuario(login, username, image, nombre, apellido, correo, birth, admin, password);
        }
        
        public System.Threading.Tasks.Task sp_AlterUsuarioAsync(PRProject.SQLTrans.LoginData login, string username, int image, string nombre, string apellido, string correo, string birth, bool admin, string password) {
            return base.Channel.sp_AlterUsuarioAsync(login, username, image, nombre, apellido, correo, birth, admin, password);
        }
        
        public PRProject.SQLTrans.Platillos[] sp_RecomendarProductos() {
            return base.Channel.sp_RecomendarProductos();
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> sp_RecomendarProductosAsync() {
            return base.Channel.sp_RecomendarProductosAsync();
        }
        
        public PRProject.SQLTrans.Platillos[] sp_RecomendarProductosPersonalizado(string user) {
            return base.Channel.sp_RecomendarProductosPersonalizado(user);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> sp_RecomendarProductosPersonalizadoAsync(string user) {
            return base.Channel.sp_RecomendarProductosPersonalizadoAsync(user);
        }
        
        public void sp_AgregarClick(PRProject.SQLTrans.LoginData login, int idplatillo, string iduser) {
            base.Channel.sp_AgregarClick(login, idplatillo, iduser);
        }
        
        public System.Threading.Tasks.Task sp_AgregarClickAsync(PRProject.SQLTrans.LoginData login, int idplatillo, string iduser) {
            return base.Channel.sp_AgregarClickAsync(login, idplatillo, iduser);
        }
        
        public System.Collections.Generic.Dictionary<int, string> getGallery() {
            return base.Channel.getGallery();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> getGalleryAsync() {
            return base.Channel.getGalleryAsync();
        }
        
        public PRProject.SQLTrans.Platillos[] buscarPlatillo(string buscar) {
            return base.Channel.buscarPlatillo(buscar);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> buscarPlatilloAsync(string buscar) {
            return base.Channel.buscarPlatilloAsync(buscar);
        }
        
        public void sp_AlterLocation(PRProject.SQLTrans.LoginData login, int id, int x, int y) {
            base.Channel.sp_AlterLocation(login, id, x, y);
        }
        
        public System.Threading.Tasks.Task sp_AlterLocationAsync(PRProject.SQLTrans.LoginData login, int id, int x, int y) {
            return base.Channel.sp_AlterLocationAsync(login, id, x, y);
        }
    }
}
