//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRProject.SQLTrans {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurantes", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Restaurantes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REFERENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RATE {
            get {
                return this.RATEField;
            }
            set {
                if ((object.ReferenceEquals(this.RATEField, value) != true)) {
                    this.RATEField = value;
                    this.RaisePropertyChanged("RATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCIA {
            get {
                return this.REFERENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.REFERENCIAField, value) != true)) {
                    this.REFERENCIAField = value;
                    this.RaisePropertyChanged("REFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ADMINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CORREO_ELECTRONICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_CUMPLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VISITASField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ADMIN {
            get {
                return this.ADMINField;
            }
            set {
                if ((this.ADMINField.Equals(value) != true)) {
                    this.ADMINField = value;
                    this.RaisePropertyChanged("ADMIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDO {
            get {
                return this.APELLIDOField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOField, value) != true)) {
                    this.APELLIDOField = value;
                    this.RaisePropertyChanged("APELLIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_ELECTRONICO {
            get {
                return this.CORREO_ELECTRONICOField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_ELECTRONICOField, value) != true)) {
                    this.CORREO_ELECTRONICOField = value;
                    this.RaisePropertyChanged("CORREO_ELECTRONICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FECHA_CUMPLE {
            get {
                return this.FECHA_CUMPLEField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_CUMPLEField, value) != true)) {
                    this.FECHA_CUMPLEField = value;
                    this.RaisePropertyChanged("FECHA_CUMPLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_USUARIOField, value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VISITAS {
            get {
                return this.VISITASField;
            }
            set {
                if ((this.VISITASField.Equals(value) != true)) {
                    this.VISITASField = value;
                    this.RaisePropertyChanged("VISITAS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Platillos", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Platillos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PLATILLOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_RESTAURANTESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PRECIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PLATILLOS {
            get {
                return this.ID_PLATILLOSField;
            }
            set {
                if ((this.ID_PLATILLOSField.Equals(value) != true)) {
                    this.ID_PLATILLOSField = value;
                    this.RaisePropertyChanged("ID_PLATILLOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_RESTAURANTES {
            get {
                return this.ID_RESTAURANTESField;
            }
            set {
                if ((this.ID_RESTAURANTESField.Equals(value) != true)) {
                    this.ID_RESTAURANTESField = value;
                    this.RaisePropertyChanged("ID_RESTAURANTES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TIPO {
            get {
                return this.ID_TIPOField;
            }
            set {
                if ((this.ID_TIPOField.Equals(value) != true)) {
                    this.ID_TIPOField = value;
                    this.RaisePropertyChanged("ID_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRECIO {
            get {
                return this.PRECIOField;
            }
            set {
                if ((this.PRECIOField.Equals(value) != true)) {
                    this.PRECIOField = value;
                    this.RaisePropertyChanged("PRECIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RATE {
            get {
                return this.RATEField;
            }
            set {
                if ((this.RATEField.Equals(value) != true)) {
                    this.RATEField = value;
                    this.RaisePropertyChanged("RATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comentarios", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class Comentarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMENTARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_COMENTARIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PLATILLOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMENTARIOS {
            get {
                return this.COMENTARIOSField;
            }
            set {
                if ((object.ReferenceEquals(this.COMENTARIOSField, value) != true)) {
                    this.COMENTARIOSField = value;
                    this.RaisePropertyChanged("COMENTARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_COMENTARIOS {
            get {
                return this.ID_COMENTARIOSField;
            }
            set {
                if ((this.ID_COMENTARIOSField.Equals(value) != true)) {
                    this.ID_COMENTARIOSField = value;
                    this.RaisePropertyChanged("ID_COMENTARIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PLATILLOS {
            get {
                return this.ID_PLATILLOSField;
            }
            set {
                if ((this.ID_PLATILLOSField.Equals(value) != true)) {
                    this.ID_PLATILLOSField = value;
                    this.RaisePropertyChanged("ID_PLATILLOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((this.ID_USUARIOField.Equals(value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASS {
            get {
                return this.PASSField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSField, value) != true)) {
                    this.PASSField = value;
                    this.RaisePropertyChanged("PASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER {
            get {
                return this.USERField;
            }
            set {
                if ((object.ReferenceEquals(this.USERField, value) != true)) {
                    this.USERField = value;
                    this.RaisePropertyChanged("USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                if ((this.isAdminField.Equals(value) != true)) {
                    this.isAdminField = value;
                    this.RaisePropertyChanged("isAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLTrans.ICrudService")]
    public interface ICrudService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/isAdmin", ReplyAction="http://tempuri.org/ICrudService/isAdminResponse")]
        bool isAdmin(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/isAdmin", ReplyAction="http://tempuri.org/ICrudService/isAdminResponse")]
        System.Threading.Tasks.Task<bool> isAdminAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetRestaurantes", ReplyAction="http://tempuri.org/ICrudService/GetRestaurantesResponse")]
        PRProject.SQLTrans.Restaurantes[] GetRestaurantes(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetRestaurantes", ReplyAction="http://tempuri.org/ICrudService/GetRestaurantesResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Restaurantes[]> GetRestaurantesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetUsuarios", ReplyAction="http://tempuri.org/ICrudService/GetUsuariosResponse")]
        PRProject.SQLTrans.Usuarios[] GetUsuarios(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetUsuarios", ReplyAction="http://tempuri.org/ICrudService/GetUsuariosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Usuarios[]> GetUsuariosAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetPlatillos", ReplyAction="http://tempuri.org/ICrudService/GetPlatillosResponse")]
        PRProject.SQLTrans.Platillos[] GetPlatillos(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetPlatillos", ReplyAction="http://tempuri.org/ICrudService/GetPlatillosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> GetPlatillosAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetComentarios", ReplyAction="http://tempuri.org/ICrudService/GetComentariosResponse")]
        PRProject.SQLTrans.Comentarios[] GetComentarios(int id_platillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetComentarios", ReplyAction="http://tempuri.org/ICrudService/GetComentariosResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.Comentarios[]> GetComentariosAsync(int id_platillo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetTiposPlatillo", ReplyAction="http://tempuri.org/ICrudService/GetTiposPlatilloResponse")]
        string[] GetTiposPlatillo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/GetTiposPlatillo", ReplyAction="http://tempuri.org/ICrudService/GetTiposPlatilloResponse")]
        System.Threading.Tasks.Task<string[]> GetTiposPlatilloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarRestaurante", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarRestauranteResponse")]
        void sp_AgregarRestaurante(PRProject.SQLTrans.LoginData login, string name, string reference, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarRestaurante", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarRestauranteResponse")]
        System.Threading.Tasks.Task sp_AgregarRestauranteAsync(PRProject.SQLTrans.LoginData login, string name, string reference, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarUsuarioResponse")]
        void sp_AgregarUsuario(string id, string nombre, string apellido, string correo, string borndate, string pass, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarUsuarioResponse")]
        System.Threading.Tasks.Task sp_AgregarUsuarioAsync(string id, string nombre, string apellido, string correo, string borndate, string pass, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_ValidarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_ValidarUsuarioResponse")]
        System.Data.DataSet sp_ValidarUsuario(string iduser, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_ValidarUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> sp_ValidarUsuarioAsync(string iduser, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarImagen", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarImagenResponse")]
        int sp_AgregarImagen(PRProject.SQLTrans.LoginData login, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarImagen", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarImagenResponse")]
        System.Threading.Tasks.Task<int> sp_AgregarImagenAsync(PRProject.SQLTrans.LoginData login, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPlatilloResponse")]
        void sp_AgregarPlatillo(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPlatilloResponse")]
        System.Threading.Tasks.Task sp_AgregarPlatilloAsync(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPunto", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPuntoResponse")]
        void sp_AgregarPunto(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarPunto", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarPuntoResponse")]
        System.Threading.Tasks.Task sp_AgregarPuntoAsync(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarEstadistica", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarEstadisticaResponse")]
        void sp_AgregarEstadistica(PRProject.SQLTrans.LoginData login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarEstadistica", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarEstadisticaResponse")]
        System.Threading.Tasks.Task sp_AgregarEstadisticaAsync(PRProject.SQLTrans.LoginData login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarComentarioResponse")]
        void sp_AgregarComentario(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarComentarioResponse")]
        System.Threading.Tasks.Task sp_AgregarComentarioAsync(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarValoracion", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarValoracionResponse")]
        void sp_AgregarValoracion(PRProject.SQLTrans.LoginData login, string idplatillo, float rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AgregarValoracion", ReplyAction="http://tempuri.org/ICrudService/sp_AgregarValoracionResponse")]
        System.Threading.Tasks.Task sp_AgregarValoracionAsync(PRProject.SQLTrans.LoginData login, string idplatillo, float rate);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_Delete", ReplyAction="http://tempuri.org/ICrudService/sp_DeleteResponse")]
        PRProject.SQLTrans.sp_DeleteResponse sp_Delete(PRProject.SQLTrans.sp_DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_Delete", ReplyAction="http://tempuri.org/ICrudService/sp_DeleteResponse")]
        System.Threading.Tasks.Task<PRProject.SQLTrans.sp_DeleteResponse> sp_DeleteAsync(PRProject.SQLTrans.sp_DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterRestaurant", ReplyAction="http://tempuri.org/ICrudService/sp_AlterRestaurantResponse")]
        void sp_AlterRestaurant(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterRestaurant", ReplyAction="http://tempuri.org/ICrudService/sp_AlterRestaurantResponse")]
        System.Threading.Tasks.Task sp_AlterRestaurantAsync(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AlterPlatilloResponse")]
        void sp_AlterPlatillo(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterPlatillo", ReplyAction="http://tempuri.org/ICrudService/sp_AlterPlatilloResponse")]
        System.Threading.Tasks.Task sp_AlterPlatilloAsync(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterComentarioResponse")]
        void sp_AlterComentario(PRProject.SQLTrans.LoginData login, int id, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterComentario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterComentarioResponse")]
        System.Threading.Tasks.Task sp_AlterComentarioAsync(PRProject.SQLTrans.LoginData login, int id, string comentario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterUsuarioResponse")]
        void sp_AlterUsuario(PRProject.SQLTrans.LoginData login, string image, string nombre, string apellido, string correo, string birth, bool admin, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudService/sp_AlterUsuario", ReplyAction="http://tempuri.org/ICrudService/sp_AlterUsuarioResponse")]
        System.Threading.Tasks.Task sp_AlterUsuarioAsync(PRProject.SQLTrans.LoginData login, string image, string nombre, string apellido, string correo, string birth, bool admin, string password);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sp_DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sp_Delete", Namespace="http://tempuri.org/", Order=0)]
        public PRProject.SQLTrans.sp_DeleteRequestBody Body;
        
        public sp_DeleteRequest() {
        }
        
        public sp_DeleteRequest(PRProject.SQLTrans.sp_DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sp_DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public PRProject.SQLTrans.LoginData login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public sp_DeleteRequestBody() {
        }
        
        public sp_DeleteRequestBody(PRProject.SQLTrans.LoginData login, string Tipo, int id) {
            this.login = login;
            this.Tipo = Tipo;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sp_DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sp_DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public PRProject.SQLTrans.sp_DeleteResponseBody Body;
        
        public sp_DeleteResponse() {
        }
        
        public sp_DeleteResponse(PRProject.SQLTrans.sp_DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sp_DeleteResponseBody {
        
        public sp_DeleteResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrudServiceChannel : PRProject.SQLTrans.ICrudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrudServiceClient : System.ServiceModel.ClientBase<PRProject.SQLTrans.ICrudService>, PRProject.SQLTrans.ICrudService {
        
        public CrudServiceClient() {
        }
        
        public CrudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isAdmin(string user) {
            return base.Channel.isAdmin(user);
        }
        
        public System.Threading.Tasks.Task<bool> isAdminAsync(string user) {
            return base.Channel.isAdminAsync(user);
        }
        
        public PRProject.SQLTrans.Restaurantes[] GetRestaurantes(int id) {
            return base.Channel.GetRestaurantes(id);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Restaurantes[]> GetRestaurantesAsync(int id) {
            return base.Channel.GetRestaurantesAsync(id);
        }
        
        public PRProject.SQLTrans.Usuarios[] GetUsuarios(string id) {
            return base.Channel.GetUsuarios(id);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Usuarios[]> GetUsuariosAsync(string id) {
            return base.Channel.GetUsuariosAsync(id);
        }
        
        public PRProject.SQLTrans.Platillos[] GetPlatillos(int id) {
            return base.Channel.GetPlatillos(id);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Platillos[]> GetPlatillosAsync(int id) {
            return base.Channel.GetPlatillosAsync(id);
        }
        
        public PRProject.SQLTrans.Comentarios[] GetComentarios(int id_platillo) {
            return base.Channel.GetComentarios(id_platillo);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.Comentarios[]> GetComentariosAsync(int id_platillo) {
            return base.Channel.GetComentariosAsync(id_platillo);
        }
        
        public string[] GetTiposPlatillo() {
            return base.Channel.GetTiposPlatillo();
        }
        
        public System.Threading.Tasks.Task<string[]> GetTiposPlatilloAsync() {
            return base.Channel.GetTiposPlatilloAsync();
        }
        
        public void sp_AgregarRestaurante(PRProject.SQLTrans.LoginData login, string name, string reference, string img) {
            base.Channel.sp_AgregarRestaurante(login, name, reference, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarRestauranteAsync(PRProject.SQLTrans.LoginData login, string name, string reference, string img) {
            return base.Channel.sp_AgregarRestauranteAsync(login, name, reference, img);
        }
        
        public void sp_AgregarUsuario(string id, string nombre, string apellido, string correo, string borndate, string pass, string img) {
            base.Channel.sp_AgregarUsuario(id, nombre, apellido, correo, borndate, pass, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarUsuarioAsync(string id, string nombre, string apellido, string correo, string borndate, string pass, string img) {
            return base.Channel.sp_AgregarUsuarioAsync(id, nombre, apellido, correo, borndate, pass, img);
        }
        
        public System.Data.DataSet sp_ValidarUsuario(string iduser, string pass) {
            return base.Channel.sp_ValidarUsuario(iduser, pass);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> sp_ValidarUsuarioAsync(string iduser, string pass) {
            return base.Channel.sp_ValidarUsuarioAsync(iduser, pass);
        }
        
        public int sp_AgregarImagen(PRProject.SQLTrans.LoginData login, string url) {
            return base.Channel.sp_AgregarImagen(login, url);
        }
        
        public System.Threading.Tasks.Task<int> sp_AgregarImagenAsync(PRProject.SQLTrans.LoginData login, string url) {
            return base.Channel.sp_AgregarImagenAsync(login, url);
        }
        
        public void sp_AgregarPlatillo(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img) {
            base.Channel.sp_AgregarPlatillo(login, nombre, precio, descripcion, tipo, restaurante, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarPlatilloAsync(PRProject.SQLTrans.LoginData login, string nombre, float precio, string descripcion, int tipo, int restaurante, string img) {
            return base.Channel.sp_AgregarPlatilloAsync(login, nombre, precio, descripcion, tipo, restaurante, img);
        }
        
        public void sp_AgregarPunto(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante) {
            base.Channel.sp_AgregarPunto(login, x, y, restaurante);
        }
        
        public System.Threading.Tasks.Task sp_AgregarPuntoAsync(PRProject.SQLTrans.LoginData login, int x, int y, int restaurante) {
            return base.Channel.sp_AgregarPuntoAsync(login, x, y, restaurante);
        }
        
        public void sp_AgregarEstadistica(PRProject.SQLTrans.LoginData login) {
            base.Channel.sp_AgregarEstadistica(login);
        }
        
        public System.Threading.Tasks.Task sp_AgregarEstadisticaAsync(PRProject.SQLTrans.LoginData login) {
            return base.Channel.sp_AgregarEstadisticaAsync(login);
        }
        
        public void sp_AgregarComentario(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario) {
            base.Channel.sp_AgregarComentario(login, idplatillo, comentario);
        }
        
        public System.Threading.Tasks.Task sp_AgregarComentarioAsync(PRProject.SQLTrans.LoginData login, string idplatillo, string comentario) {
            return base.Channel.sp_AgregarComentarioAsync(login, idplatillo, comentario);
        }
        
        public void sp_AgregarValoracion(PRProject.SQLTrans.LoginData login, string idplatillo, float rate) {
            base.Channel.sp_AgregarValoracion(login, idplatillo, rate);
        }
        
        public System.Threading.Tasks.Task sp_AgregarValoracionAsync(PRProject.SQLTrans.LoginData login, string idplatillo, float rate) {
            return base.Channel.sp_AgregarValoracionAsync(login, idplatillo, rate);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRProject.SQLTrans.sp_DeleteResponse PRProject.SQLTrans.ICrudService.sp_Delete(PRProject.SQLTrans.sp_DeleteRequest request) {
            return base.Channel.sp_Delete(request);
        }
        
        public void sp_Delete(PRProject.SQLTrans.LoginData login, string Tipo, int id) {
            PRProject.SQLTrans.sp_DeleteRequest inValue = new PRProject.SQLTrans.sp_DeleteRequest();
            inValue.Body = new PRProject.SQLTrans.sp_DeleteRequestBody();
            inValue.Body.login = login;
            inValue.Body.Tipo = Tipo;
            inValue.Body.id = id;
            PRProject.SQLTrans.sp_DeleteResponse retVal = ((PRProject.SQLTrans.ICrudService)(this)).sp_Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PRProject.SQLTrans.sp_DeleteResponse> PRProject.SQLTrans.ICrudService.sp_DeleteAsync(PRProject.SQLTrans.sp_DeleteRequest request) {
            return base.Channel.sp_DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PRProject.SQLTrans.sp_DeleteResponse> sp_DeleteAsync(PRProject.SQLTrans.LoginData login, string Tipo, int id) {
            PRProject.SQLTrans.sp_DeleteRequest inValue = new PRProject.SQLTrans.sp_DeleteRequest();
            inValue.Body = new PRProject.SQLTrans.sp_DeleteRequestBody();
            inValue.Body.login = login;
            inValue.Body.Tipo = Tipo;
            inValue.Body.id = id;
            return ((PRProject.SQLTrans.ICrudService)(this)).sp_DeleteAsync(inValue);
        }
        
        public void sp_AlterRestaurant(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia) {
            base.Channel.sp_AlterRestaurant(login, id, img, point, nombre, referencia);
        }
        
        public System.Threading.Tasks.Task sp_AlterRestaurantAsync(PRProject.SQLTrans.LoginData login, int id, int img, int point, string nombre, string referencia) {
            return base.Channel.sp_AlterRestaurantAsync(login, id, img, point, nombre, referencia);
        }
        
        public void sp_AlterPlatillo(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion) {
            base.Channel.sp_AlterPlatillo(login, id, restaurant, img, tipo, nombre, precio, descripcion);
        }
        
        public System.Threading.Tasks.Task sp_AlterPlatilloAsync(PRProject.SQLTrans.LoginData login, int id, int restaurant, int img, int tipo, string nombre, float precio, string descripcion) {
            return base.Channel.sp_AlterPlatilloAsync(login, id, restaurant, img, tipo, nombre, precio, descripcion);
        }
        
        public void sp_AlterComentario(PRProject.SQLTrans.LoginData login, int id, string comentario) {
            base.Channel.sp_AlterComentario(login, id, comentario);
        }
        
        public System.Threading.Tasks.Task sp_AlterComentarioAsync(PRProject.SQLTrans.LoginData login, int id, string comentario) {
            return base.Channel.sp_AlterComentarioAsync(login, id, comentario);
        }
        
        public void sp_AlterUsuario(PRProject.SQLTrans.LoginData login, string image, string nombre, string apellido, string correo, string birth, bool admin, string password) {
            base.Channel.sp_AlterUsuario(login, image, nombre, apellido, correo, birth, admin, password);
        }
        
        public System.Threading.Tasks.Task sp_AlterUsuarioAsync(PRProject.SQLTrans.LoginData login, string image, string nombre, string apellido, string correo, string birth, bool admin, string password) {
            return base.Channel.sp_AlterUsuarioAsync(login, image, nombre, apellido, correo, birth, admin, password);
        }
    }
}
