//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototipo.SQLTrans {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLTrans.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sp_AgregarRestaurante", ReplyAction="http://tempuri.org/IService1/sp_AgregarRestauranteResponse")]
        void sp_AgregarRestaurante(string name, string reference, string img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sp_AgregarRestaurante", ReplyAction="http://tempuri.org/IService1/sp_AgregarRestauranteResponse")]
        System.Threading.Tasks.Task sp_AgregarRestauranteAsync(string name, string reference, string img);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Prototipo.SQLTrans.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Prototipo.SQLTrans.IService1>, Prototipo.SQLTrans.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sp_AgregarRestaurante(string name, string reference, string img) {
            base.Channel.sp_AgregarRestaurante(name, reference, img);
        }
        
        public System.Threading.Tasks.Task sp_AgregarRestauranteAsync(string name, string reference, string img) {
            return base.Channel.sp_AgregarRestauranteAsync(name, reference, img);
        }
    }
}
